language: go
branches:
  only:
    - main
    - fatewa

before_install:
  - export TZ='Asia/Shanghai'

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.82.1/hugo_0.82.1_Linux-64bit.tar.gz
  - tar -xzvf hugo_0.82.1_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version
  - rm -rf public

script:
  - pwd && ls
  - hugo -F
  - echo 'build ok!'

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: fatewa
